### ISSUE TITLE
Simplebar ?

### ISSUE THREAD

**Issue by mathieu-roquet** [guimelcode/new_portique_theme#4]

**Comment by mathieu-roquet** [comment]
Trouver une solution pour rendre discrète la barre de scroll pour une majorité de navigateurs

Par exemple : Ajout du plugin Simplebar https://github.com/Grsmto/simplebar sur :
#app > div > .bxslider > .swiper-slide-active

**Comment by guimelcode** [comment]
Mis en pratique, problème en héritage sur l'animation de chargement des article des Archives.
