### ISSUE TITLE
Custom template

### ISSUE THREAD

**Issue by mathieu-roquet** [guimelcode/new_portique_theme#5]
- faire fonctionner template un  template spécifique image à droite (médiations > scolaires + jeunes, information > équipe)
Template custom pour l'intégration google maps dans infos / nous trouver

**Comment by guimelcode** [comment]
Changement de plan !
Plus de custom post type Wordpress, mais changement d'appel de template-parts.
D'ailleurs ce dossier a été enrichi et rendu plus lisible : chaque page peut se voir attribuer un template du sous dossier template-parts/pages.
Les ajouts sont en cours.

**Comment by guimelcode** [comment]
Les attributions sont faites.
Dispo pour faire la structure Html pour mise en page.
