### ISSUE TITLE
Href Langage

### ISSUE THREAD

**Issue by guimelcode** [guimelcode/new_portique_theme#7]
Petit problème d'href pour les liens pour sélectionner la langue : 
<img width="595" alt="capture d ecran 2017-10-01 a 23 11 27" src="https://user-images.githubusercontent.com/5241100/31059026-f70f24e2-a6fd-11e7-9bd5-6dc85d064d23.png">

**Comment by mathieu-roquet** [comment]
![screenshot_20171003_233545](https://user-images.githubusercontent.com/32080791/31150416-c37f20b8-a893-11e7-89b4-dfbecefaddf2.png)
Je vois d'où vient l'erreur, j'avais tenté de mofifier irectement le contenu des liens dans la configuration, plutôt que les cibler en CSS avec Content
